CREATE USER IF NOT EXISTS SA SALT 'ca5a98c4180fcb28' HASH 'a3c4fc20b7845c0842f836cad3aac1af44c2d6c5205889659ad055665808569b' ADMIN;
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 240;
CREATE CACHED TABLE PUBLIC.BOARD(
    BOARD_ID BIGINT NOT NULL,
    CONTENT CLOB,
    CREATED_DATE_TIME TIMESTAMP,
    HIT INTEGER DEFAULT 0 NOT NULL,
    MODIFIED_DATE_TIME TIMESTAMP,
    TITLE VARCHAR(255) NOT NULL,
    MEMBER_ID BIGINT
);
ALTER TABLE PUBLIC.BOARD ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(BOARD_ID);
-- 11 +/- SELECT COUNT(*) FROM PUBLIC.BOARD;
CREATE CACHED TABLE PUBLIC.BOARD_IMAGE(
    ID BIGINT NOT NULL,
    URL VARCHAR(255),
    BOARD_BOARD_ID BIGINT
);
ALTER TABLE PUBLIC.BOARD_IMAGE ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
-- 18 +/- SELECT COUNT(*) FROM PUBLIC.BOARD_IMAGE;
CREATE CACHED TABLE PUBLIC.BOARD_LIKE(
    ID BIGINT NOT NULL,
    BOARD_ID BIGINT,
    MEMBER_ID BIGINT
);
ALTER TABLE PUBLIC.BOARD_LIKE ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.BOARD_LIKE;
CREATE CACHED TABLE PUBLIC.MEMBER(
    MEMBER_ID BIGINT NOT NULL,
    ABOUT VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    IMAGE VARCHAR(255),
    JOB VARCHAR(255),
    NAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255),
    USERNAME VARCHAR(20) NOT NULL
);
ALTER TABLE PUBLIC.MEMBER ADD CONSTRAINT PUBLIC.CONSTRAINT_87 PRIMARY KEY(MEMBER_ID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.MEMBER;
CREATE CACHED TABLE PUBLIC.MEMBER_FOLLOW(
    ID BIGINT NOT NULL,
    FOLLOW_ID BIGINT,
    MEMBER_ID BIGINT
);
ALTER TABLE PUBLIC.MEMBER_FOLLOW ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEMBER_FOLLOW;
CREATE CACHED TABLE PUBLIC.COMMENT(
    COMMENT_ID BIGINT NOT NULL,
    CONTENT VARCHAR(100) NOT NULL,
    BOARD_BOARD_ID BIGINT,
    MEMBER_ID BIGINT,
    BOARD_ID BIGINT
);
ALTER TABLE PUBLIC.COMMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_63 PRIMARY KEY(COMMENT_ID);
-- 38 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT;
ALTER TABLE PUBLIC.MEMBER ADD CONSTRAINT PUBLIC.UK_GC3JMN7C2ABYO3WF6SYLN5T2I UNIQUE(USERNAME);
ALTER TABLE PUBLIC.BOARD_LIKE ADD CONSTRAINT PUBLIC.UKC9LA0M8KFC21JFW85QNUN4PN4 UNIQUE(MEMBER_ID, BOARD_ID);
ALTER TABLE PUBLIC.COMMENT ADD CONSTRAINT PUBLIC.FKMRRRPI513SSU63I2783JYIV9M FOREIGN KEY(MEMBER_ID) REFERENCES PUBLIC.MEMBER(MEMBER_ID) NOCHECK;
ALTER TABLE PUBLIC.BOARD_IMAGE ADD CONSTRAINT PUBLIC.FK7V630EOL4DNVOLWHXFFMR29G1 FOREIGN KEY(BOARD_BOARD_ID) REFERENCES PUBLIC.BOARD(BOARD_ID) NOCHECK;
ALTER TABLE PUBLIC.BOARD_LIKE ADD CONSTRAINT PUBLIC.FKK7RXM8VL1PTQQHWDJ2SJMLPVQ FOREIGN KEY(BOARD_ID) REFERENCES PUBLIC.BOARD(BOARD_ID) NOCHECK;
ALTER TABLE PUBLIC.COMMENT ADD CONSTRAINT PUBLIC.FK9TL7MC4O8S8A9O1IPXIPVPI22 FOREIGN KEY(BOARD_BOARD_ID) REFERENCES PUBLIC.BOARD(BOARD_ID) NOCHECK;
ALTER TABLE PUBLIC.BOARD ADD CONSTRAINT PUBLIC.FKSDS8OX89WWF6AIHINAR49RMFY FOREIGN KEY(MEMBER_ID) REFERENCES PUBLIC.MEMBER(MEMBER_ID) NOCHECK;
ALTER TABLE PUBLIC.COMMENT ADD CONSTRAINT PUBLIC.FKLIJ9OOR1NAV89JEAT35S6KBP1 FOREIGN KEY(BOARD_ID) REFERENCES PUBLIC.BOARD(BOARD_ID) NOCHECK;
ALTER TABLE PUBLIC.BOARD_LIKE ADD CONSTRAINT PUBLIC.FKTIGEW3M6H54WECU5UDC0P3QIK FOREIGN KEY(MEMBER_ID) REFERENCES PUBLIC.MEMBER(MEMBER_ID) NOCHECK;
ALTER TABLE PUBLIC.MEMBER_FOLLOW ADD CONSTRAINT PUBLIC.FKC9VUX75WRYPGT9EJ8YG0K6VYA FOREIGN KEY(MEMBER_ID) REFERENCES PUBLIC.MEMBER(MEMBER_ID) NOCHECK;
ALTER TABLE PUBLIC.MEMBER_FOLLOW ADD CONSTRAINT PUBLIC.FK9ELQK855UGMT9JSL2TG0T7BV4 FOREIGN KEY(FOLLOW_ID) REFERENCES PUBLIC.MEMBER(MEMBER_ID) NOCHECK;